import { PlanId, SubscriptionStatus, TableStatus, UserRole } from '@prisma/client';

export const demoSeed = {
  trialDays: 14,
  tenant: {
    id: 'clseedtenantgeneral000000001',
    slug: 'general-burguer',
    name: 'General Burguer',
    address: 'Rua das Hamburguerias, 42',
    city: 'Sao Paulo',
    phone: '11999998888',
    whatsapp: '5511999998888',
    hours: 'Seg-Sab 11h-23h',
    logoUrl: null as string | null,
    planId: PlanId.MESA,
    maxTables: 15,
    deliveryAreas: ['Centro', 'Jardins', 'Pinheiros'],
    paymentMethods: ['Pix', 'Credito', 'Debito'],
  },
  owner: {
    id: 'clseedusercarlos0000000001',
    name: 'Carlos Silva',
    email: 'carlos@generalburguer.com',
    password: 'demo123',
    passwordHash: '$2a$10$hpv/UmNB4T4EfuQjO93Ml.zOdFqQ9fzJ0lO7o7b6zerzgiffJ2HPi',
    role: UserRole.OWNER,
  },
  subscription: {
    id: 'clseedsubscription000000001',
    status: SubscriptionStatus.TRIALING,
  },
  categories: [
    {
      id: 'clseedcategoryburgers000001',
      name: 'Burgers',
      icon: 'burger',
      sortOrder: 1,
    },
    {
      id: 'clseedcategorysides000000001',
      name: 'Acompanhamentos',
      icon: 'utensils',
      sortOrder: 2,
    },
    {
      id: 'clseedcategorydrinks00000001',
      name: 'Bebidas',
      icon: 'cup-soda',
      sortOrder: 3,
    },
  ],
  modifierGroup: {
    id: 'clseedmodifiergroup000000001',
    name: 'Adicionais',
    description: null as string | null,
    isRequired: false,
    minSelections: 0,
    maxSelections: 3,
    sortOrder: 0,
    options: [
      {
        id: 'clseedmodifieroption0000001',
        name: 'Bacon extra',
        priceCents: 500,
        sortOrder: 0,
        isActive: true,
      },
      {
        id: 'clseedmodifieroption0000002',
        name: 'Cheddar extra',
        priceCents: 400,
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 'clseedmodifieroption0000003',
        name: 'Ovo',
        priceCents: 300,
        sortOrder: 2,
        isActive: true,
      },
    ],
  },
  menuItems: [
    {
      id: 'clseedmenuitemsmash00000001',
      categoryId: 'clseedcategoryburgers000001',
      name: 'Smash Classico',
      description: 'Dois smash burgers, cheddar e molho da casa.',
      priceCents: 3290,
      isBestSeller: true,
      isActive: true,
    },
    {
      id: 'clseedmenuitemgeneral000001',
      categoryId: 'clseedcategoryburgers000001',
      name: 'General Burguer',
      description: 'Hamburguer artesanal com provolone e maionese trufada.',
      priceCents: 3990,
      isBestSeller: true,
      isActive: true,
    },
    {
      id: 'clseedmenuitemsides00000001',
      categoryId: 'clseedcategorysides000000001',
      name: 'Batata Rustica',
      description: 'Batata rustica com ervas finas.',
      priceCents: 1890,
      isBestSeller: false,
      isActive: true,
    },
    {
      id: 'clseedmenuitemcoke00000001',
      categoryId: 'clseedcategorydrinks00000001',
      name: 'Coca-Cola',
      description: 'Lata 350ml',
      priceCents: 790,
      isBestSeller: false,
      isActive: true,
    },
    {
      id: 'clseedmenuitemjuice0000001',
      categoryId: 'clseedcategorydrinks00000001',
      name: 'Suco Natural',
      description: 'Laranja ou limao, 400ml.',
      priceCents: 1290,
      isBestSeller: false,
      isActive: true,
    },
  ],
  menuItemModifierGroups: [
    {
      id: 'clseeditemgroup000000000001',
      menuItemId: 'clseedmenuitemsmash00000001',
      modifierGroupId: 'clseedmodifiergroup000000001',
      sortOrder: 0,
    },
  ],
  tables: [
    {
      id: 'clseedtable000000000000001',
      number: 1,
      status: TableStatus.AVAILABLE,
    },
    {
      id: 'clseedtable000000000000002',
      number: 2,
      status: TableStatus.OCCUPIED,
    },
  ],
} as const;
